from __future__ import annotations
import collections.abc
import numpy
import numpy.typing
import scipy.sparse
import typing
__all__: list[str] = ['BSpline', 'Basis', 'BoundaryValue', 'Condition1d', 'Condition2d', 'Constraint', 'DirectConstraint', 'Element1d', 'Element2d', 'Field', 'FieldType', 'Function1d', 'Function2d', 'GaussLegendre1d', 'GaussLegendre2d', 'LagrangeBoundaryCondition2d', 'LinearConstraint', 'LinearElasticProblem1d', 'LinearElasticProblem2d', 'LoadBoundaryCondition2d', 'Material1d', 'Material2d', 'NURBS', 'Patch1d', 'Patch2d', 'PatchBoundary2d', 'PenaltyBoundaryCondition2d', 'PenaltyCouplingCondition2d', 'PlaneStress2d', 'QuadratureRule1d', 'QuadratureRule2d', 'ShellKirchhoffLove3p', 'ShellReissnerMindlin4p', 'ShellReissnerMindlin5p', 'UniaxialStress1d', 'bezier_anchor_params', 'eval_quadrature_data', 'export_bezier_vtm', 'export_bezier_vtu', 'inner_product']
class BSpline(Basis):
    @staticmethod
    def clamped_uniform(degree: typing.SupportsInt | typing.SupportsIndex, num_basis: typing.SupportsInt | typing.SupportsIndex) -> BSpline:
        ...
class Basis:
    def degree(self) -> int:
        ...
    def elevate_degree(self) -> tuple[Basis, typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, n]"]]:
        ...
    def eval_all(self, u: typing.Annotated[numpy.typing.ArrayLike, numpy.float64], order: typing.SupportsInt | typing.SupportsIndex = 0) -> list[typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, n]"]]:
        ...
    def find_span(self, u: typing.SupportsFloat | typing.SupportsIndex) -> int:
        ...
    def greville_abscissae(self) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, 1]"]:
        ...
    def insert_knot(self, u: typing.SupportsFloat | typing.SupportsIndex) -> tuple[Basis, typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, n]"]]:
        ...
    def knots(self) -> numpy.typing.NDArray[numpy.float64]:
        ...
    def num_basis(self) -> int:
        ...
    def num_intervals(self) -> int:
        ...
class BoundaryValue:
    def __init__(self, field: Field) -> None:
        ...
class Condition1d:
    pass
class Condition2d:
    pass
class Constraint:
    pass
class DirectConstraint(Constraint):
    @typing.overload
    def __init__(self, dofs: typing.Annotated[numpy.typing.ArrayLike, numpy.int32, "[m, 1]"], values: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[m, 1]"]) -> None:
        ...
    @typing.overload
    def __init__(self, dofs: typing.Annotated[numpy.typing.ArrayLike, numpy.int32, "[m, 1]"], value: typing.SupportsFloat | typing.SupportsIndex) -> None:
        ...
    def dofs(self) -> typing.Annotated[numpy.typing.NDArray[numpy.int32], "[m, 1]"]:
        ...
    def values(self) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, 1]"]:
        ...
class Element1d:
    def displacement_shape_matrix(self, patch: Patch1d, params: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[m, 1]"]) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, n]"]:
        ...
    def primal_shape_matrix(self, patch: Patch1d, params: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[m, 1]"]) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, n]"]:
        ...
    def rotation_shape_matrix(self, patch: Patch1d, params: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[m, 1]"]) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, n]"]:
        ...
    def strain_matrix(self, patch: Patch1d, params: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[m, 1]"]) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, n]"]:
        ...
    def stress_shape_matrix(self, patch: Patch1d, params: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[m, 1]"]) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, n]"]:
        ...
class Element2d:
    def displacement_shape_matrix(self, patch: Patch2d, params: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[m, 2]"]) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, n]"]:
        ...
    def primal_shape_matrix(self, patch: Patch2d, params: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[m, 2]"]) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, n]"]:
        ...
    def rotation_shape_matrix(self, patch: Patch2d, params: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[m, 2]"]) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, n]"]:
        ...
    def strain_matrix(self, patch: Patch2d, params: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[m, 2]"]) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, n]"]:
        ...
    def stress_shape_matrix(self, patch: Patch2d, params: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[m, 2]"]) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, n]"]:
        ...
class Field:
    U_X: typing.ClassVar[Field]
    U_Y: typing.ClassVar[Field]
    U_Z: typing.ClassVar[Field]
    U_N: typing.ClassVar[Field]
    U_S: typing.ClassVar[Field]
    ROT_X: typing.ClassVar[Field]
    ROT_Y: typing.ClassVar[Field]
    ROT_Z: typing.ClassVar[Field]
    ROT_N: typing.ClassVar[Field]
    ROT_S: typing.ClassVar[Field]
    __members__: typing.ClassVar[dict[str, Field]]
    def __init__(self, value: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    def __int__(self) -> int:
        ...
    @property
    def name(self) -> str:
        ...
    @property
    def value(self) -> int:
        ...
class FieldType:
    """
    Members:
    
      PRIMAL
    
      DISPLACEMENT
    
      ROTATION
    
      STRAIN
    
      STRESS
    """
    DISPLACEMENT: typing.ClassVar[FieldType]  # value = <FieldType.DISPLACEMENT: 1>
    PRIMAL: typing.ClassVar[FieldType]  # value = <FieldType.PRIMAL: 0>
    ROTATION: typing.ClassVar[FieldType]  # value = <FieldType.ROTATION: 2>
    STRAIN: typing.ClassVar[FieldType]  # value = <FieldType.STRAIN: 3>
    STRESS: typing.ClassVar[FieldType]  # value = <FieldType.STRESS: 4>
    __members__: typing.ClassVar[dict[str, FieldType]]  # value = {'PRIMAL': <FieldType.PRIMAL: 0>, 'DISPLACEMENT': <FieldType.DISPLACEMENT: 1>, 'ROTATION': <FieldType.ROTATION: 2>, 'STRAIN': <FieldType.STRAIN: 3>, 'STRESS': <FieldType.STRESS: 4>}
    @typing.overload
    def __eq__(self, other: FieldType) -> bool:
        ...
    @typing.overload
    def __eq__(self, other: typing.Any) -> bool:
        ...
    def __getstate__(self) -> int:
        ...
    def __hash__(self) -> int:
        ...
    def __index__(self) -> int:
        ...
    def __init__(self, value: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    def __int__(self) -> int:
        ...
    @typing.overload
    def __ne__(self, other: FieldType) -> bool:
        ...
    @typing.overload
    def __ne__(self, other: typing.Any) -> bool:
        ...
    def __repr__(self) -> str:
        ...
    def __setstate__(self, state: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    def __str__(self) -> str:
        ...
    @property
    def name(self) -> str:
        ...
    @property
    def value(self) -> int:
        ...
class Function1d:
    def __call__(self, params: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[m, 1]"]) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, n]"]:
        ...
    def __init__(self, u: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[m, 1]"], element: Element1d, patch: Patch1d, field: FieldType) -> None:
        ...
class Function2d:
    def __call__(self, params: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[m, 2]"]) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, n]"]:
        ...
    def __init__(self, u: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[m, 1]"], element: Element2d, patch: Patch2d, field: FieldType) -> None:
        ...
class GaussLegendre1d(QuadratureRule1d):
    def __init__(self, num_pts: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
class GaussLegendre2d(QuadratureRule2d):
    def __init__(self, num_pts: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
class LagrangeBoundaryCondition2d(Condition2d):
    def __init__(self, boundary: PatchBoundary2d, element: Element2d, quadrature: QuadratureRule1d) -> None:
        ...
    def add(self, field: BoundaryValue, value: typing.SupportsFloat | typing.SupportsIndex = 0.0) -> LagrangeBoundaryCondition2d:
        ...
class LinearConstraint(Constraint):
    def __init__(self, slaves: typing.Annotated[numpy.typing.ArrayLike, numpy.int32, "[m, 1]"], masters: typing.Annotated[numpy.typing.ArrayLike, numpy.int32, "[m, n]"], weights: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[m, 1]"], constant: typing.SupportsFloat | typing.SupportsIndex) -> None:
        ...
    def constant(self) -> float:
        ...
    def masters(self) -> typing.Annotated[numpy.typing.NDArray[numpy.int32], "[m, n]"]:
        ...
    def slaves(self) -> typing.Annotated[numpy.typing.NDArray[numpy.int32], "[m, 1]"]:
        ...
    def weights(self) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, 1]"]:
        ...
class LinearElasticProblem1d:
    @typing.overload
    def __init__(self, patch: Patch1d, element: Element1d, quadrature: QuadratureRule1d) -> None:
        ...
    @typing.overload
    def __init__(self, patches: collections.abc.Sequence[Patch1d], elements: collections.abc.Sequence[Element1d], quadratures: collections.abc.Sequence[QuadratureRule1d]) -> None:
        ...
    def add_condition(self, condition: Condition1d) -> None:
        ...
    @typing.overload
    def add_constraint(self, constraint: DirectConstraint) -> None:
        ...
    @typing.overload
    def add_constraint(self, constraint: Constraint) -> None:
        ...
    @typing.overload
    def add_domain_load(self, patch: Patch1d, value: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[m, 1]"]) -> None:
        ...
    @typing.overload
    def add_domain_load(self, patch: Patch1d, load_fn: collections.abc.Callable[[typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[m, n]"]], typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, n]"]]) -> None:
        ...
    def add_patch(self, patch: Patch1d, element: Element1d, quadrature: QuadratureRule1d) -> int:
        ...
    def assemble(self) -> tuple[scipy.sparse.csc_matrix, typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, 1]"]]:
        ...
class LinearElasticProblem2d:
    @typing.overload
    def __init__(self) -> None:
        ...
    @typing.overload
    def __init__(self, patch: Patch2d, element: Element2d, quadrature: QuadratureRule2d) -> None:
        ...
    @typing.overload
    def __init__(self, patches: collections.abc.Sequence[Patch2d], elements: collections.abc.Sequence[Element2d], quadratures: collections.abc.Sequence[QuadratureRule2d]) -> None:
        ...
    def add_condition(self, condition: Condition2d) -> None:
        ...
    @typing.overload
    def add_constraint(self, constraint: DirectConstraint) -> None:
        ...
    @typing.overload
    def add_constraint(self, constraint: Constraint) -> None:
        ...
    @typing.overload
    def add_domain_load(self, patch: Patch2d, value: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[m, 1]"]) -> None:
        ...
    @typing.overload
    def add_domain_load(self, patch: Patch2d, load_fn: collections.abc.Callable[[typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[m, n]"]], typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, n]"]]) -> None:
        ...
    def add_patch(self, patch: Patch2d, element: Element2d, quadrature: QuadratureRule2d) -> int:
        ...
    def assemble(self) -> tuple[scipy.sparse.csc_matrix, typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, 1]"]]:
        ...
class LoadBoundaryCondition2d(Condition2d):
    def __init__(self, boundary: PatchBoundary2d, element: Element2d, quadrature: QuadratureRule1d) -> None:
        ...
    @typing.overload
    def add(self, field: BoundaryValue, value: typing.SupportsFloat | typing.SupportsIndex = 0.0) -> LoadBoundaryCondition2d:
        ...
    @typing.overload
    def add(self, field: BoundaryValue, values: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[m, 1]"]) -> LoadBoundaryCondition2d:
        ...
class Material1d:
    def bending_stiffness(self) -> float:
        ...
    def shear_modulus(self) -> float:
        ...
    def shear_stiffness(self) -> float:
        ...
class Material2d:
    def bending_stiffness(self) -> float:
        ...
    def shear_stiffness(self) -> float:
        ...
class NURBS(Basis):
    @staticmethod
    def clamped_uniform(degree: typing.SupportsInt | typing.SupportsIndex, num_basis: typing.SupportsInt | typing.SupportsIndex, weights: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[m, 1]"]) -> NURBS:
        ...
    def weights(self) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, 1]"]:
        ...
class Patch1d:
    def __init__(self, basis: Basis, control_points: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[m, 3]"]) -> None:
        ...
    def control_pts(self) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, 3]"]:
        ...
    def elevate_degree(self, dir: typing.SupportsInt | typing.SupportsIndex) -> Patch1d:
        ...
    def eval_geometry(self, params: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[m, 1]"]) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, 3]"]:
        ...
    def insert_knot(self, dir: typing.SupportsInt | typing.SupportsIndex, u: typing.SupportsFloat | typing.SupportsIndex) -> Patch1d:
        ...
class Patch2d:
    def __init__(self, basis_u: Basis, basis_v: Basis, control_points: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[m, 3]"]) -> None:
        ...
    def control_pts(self) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, 3]"]:
        ...
    def elevate_degree(self, dir: typing.SupportsInt | typing.SupportsIndex) -> Patch2d:
        ...
    def eval_geometry(self, params: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[m, 2]"]) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, 3]"]:
        ...
    def insert_knot(self, dir: typing.SupportsInt | typing.SupportsIndex, u: typing.SupportsFloat | typing.SupportsIndex) -> Patch2d:
        ...
class PatchBoundary2d(Patch1d):
    def __init__(self, parent: Patch2d, param_dim: typing.SupportsInt | typing.SupportsIndex, at_start: bool) -> None:
        ...
    def at_start(self) -> bool:
        ...
    def displacement_dofs(self) -> list[int]:
        ...
    def param_dim(self) -> int:
        ...
    def rotation_dofs(self) -> list[int]:
        ...
class PenaltyBoundaryCondition2d(Condition2d):
    def __init__(self, boundary: PatchBoundary2d, element: Element2d, quadrature: QuadratureRule1d) -> None:
        ...
    def add(self, field: BoundaryValue, penalty: typing.SupportsFloat | typing.SupportsIndex, value: typing.SupportsFloat | typing.SupportsIndex = 0.0) -> PenaltyBoundaryCondition2d:
        ...
class PenaltyCouplingCondition2d(Condition2d):
    def __init__(self, boundary_a: PatchBoundary2d, boundary_b: PatchBoundary2d, element: Element2d, quadrature: QuadratureRule1d) -> None:
        ...
    def add(self, field: BoundaryValue, penalty: typing.SupportsFloat | typing.SupportsIndex) -> PenaltyCouplingCondition2d:
        ...
    def couple_displacement(self, penalty: typing.SupportsFloat | typing.SupportsIndex) -> PenaltyCouplingCondition2d:
        ...
    def couple_kinematics(self, penalty_disp: typing.SupportsFloat | typing.SupportsIndex, penalty_rot: typing.SupportsFloat | typing.SupportsIndex) -> PenaltyCouplingCondition2d:
        ...
class PlaneStress2d(Material2d):
    def __init__(self, E: typing.SupportsFloat | typing.SupportsIndex, nu: typing.SupportsFloat | typing.SupportsIndex, t: typing.SupportsFloat | typing.SupportsIndex, k: typing.SupportsFloat | typing.SupportsIndex = 0.8333333333333334, rho: typing.SupportsFloat | typing.SupportsIndex = 0.0) -> None:
        ...
class QuadratureRule1d:
    def points(self) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, 1]"]:
        ...
    def weights(self) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, 1]"]:
        ...
class QuadratureRule2d:
    @typing.overload
    def __init__(self, rule: QuadratureRule1d) -> None:
        ...
    @typing.overload
    def __init__(self, rules: typing.Annotated[collections.abc.Sequence[QuadratureRule1d], "FixedSize(2)"]) -> None:
        ...
    def points(self) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, 2]"]:
        ...
    def weights(self) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, 1]"]:
        ...
class ShellKirchhoffLove3p(Element2d):
    def __init__(self, material: PlaneStress2d) -> None:
        ...
class ShellReissnerMindlin4p(Element2d):
    def __init__(self, material: PlaneStress2d) -> None:
        ...
class ShellReissnerMindlin5p(Element2d):
    def __init__(self, material: PlaneStress2d) -> None:
        ...
class UniaxialStress1d(Material1d):
    def __init__(self, E: typing.SupportsFloat | typing.SupportsIndex, nu: typing.SupportsFloat | typing.SupportsIndex, A: typing.SupportsFloat | typing.SupportsIndex, I22: typing.SupportsFloat | typing.SupportsIndex, k22: typing.SupportsFloat | typing.SupportsIndex = 0.8333333333333334, rho: typing.SupportsFloat | typing.SupportsIndex = 0.0, I33: typing.SupportsFloat | typing.SupportsIndex = 0.0, k33: typing.SupportsFloat | typing.SupportsIndex = 0.0, J: typing.SupportsFloat | typing.SupportsIndex = 0.0) -> None:
        ...
def bezier_anchor_params(patch: Patch2d) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, 2]"]:
    ...
def export_bezier_vtm(path: str, patches: collections.abc.Sequence[Patch2d], point_data: collections.abc.Sequence[collections.abc.Mapping[str, typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[m, n]"]]], point_data_extracted: collections.abc.Sequence[collections.abc.Mapping[str, typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[m, n]"]]], patch_names: collections.abc.Sequence[str], title: str, binary: bool) -> None:
    ...
def export_bezier_vtu(path: str, patches: collections.abc.Sequence[Patch2d], point_data: collections.abc.Sequence[collections.abc.Mapping[str, typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[m, n]"]]], point_data_extracted: collections.abc.Sequence[collections.abc.Mapping[str, typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[m, n]"]]], title: str, binary: bool) -> None:
    ...
@typing.overload
def eval_quadrature_data(patch: Patch1d, quadrature: QuadratureRule1d) -> tuple[typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, 1]"], typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, 1]"]]:
    ...
@typing.overload
def eval_quadrature_data(patch: Patch2d, quadrature: QuadratureRule2d) -> tuple[typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, 2]"], typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, 1]"]]:
    ...
@typing.overload
def inner_product(patch: Patch1d, quadrature: QuadratureRule1d, f_vals: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[m, n]"], g_vals: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[m, n]"]) -> float:
    ...
@typing.overload
def inner_product(patch: Patch2d, quadrature: QuadratureRule2d, f_vals: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[m, n]"], g_vals: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[m, n]"]) -> float:
    ...
